# Generated by Django 5.1.1 on 2024-10-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_delete_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/'),
        ),
    ]
